app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: "@AppBundle/Controller/Admin"
    prefix: /admin
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"