# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
      # Api Listeners
      app.api.request_listener:
         class: AppBundle\EventListener\ApiRequestListener
         arguments: ["@serializer"]
         tags:
             - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

      app.api.exception_listener:
         class: AppBundle\EventListener\ExceptionListener
         tags:
             - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }


      # Validators
      app.validator.duplicate_email:
         class: AppBundle\Validator\DuplicateEmailConstraintValidator
         arguments: [ "@doctrine.orm.entity_manager" ]
         tags:
              - { name: validator.constraint_validator, alias: duplicate_email_validator }

      # Doctrine Subscribers
      app.corporation.subscriber:
          class: AppBundle\Subscriber\CorporationSubscriber
          arguments: [ "@security.token_storage" ]
          tags:
              - { name: doctrine.event_subscriber, connection: default }

      app.api_credentials.subscriber:
          class: AppBundle\Subscriber\ApiCredentialsSubscriber
          arguments: [ "@security.token_storage", "@app.account.manager" ]
          tags:
              - { name: doctrine.event_subscriber, connection: default }

      # Dispatchers
      app.task.dispatcher:
          class: AppBundle\EventListener\Dispatcher

      # Task Events
      app.task.coporation.new:
          class: AppBundle\EventListener\Corporation\NewCorporationListener
          arguments: [ "@tarioch.pheal.factory" ]
          tags:
              - { name: app.task.subscriber }

      app.task.belated_listener:
          class: AppBundle\EventListener\BelatedTaskListener
          arguments: [ "@app.task.dispatcher" ]

      # Manager
      app.corporation.manager:
          arguments: [ "@tarioch.pheal.factory" ]
          class: AppBundle\Service\Manager\CorporationManager

      app.account.manager:
          arguments: [ "@tarioch.pheal.factory" ]
          class: AppBundle\Service\Manager\AccountManager
