# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
      # Api Listeners
      app.api.request_listener:
         class: AppBundle\EventListener\ApiRequestListener
         arguments: ["@serializer"]
         tags:
             - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

      app.api.exception_listener:
         class: AppBundle\EventListener\ExceptionListener
         tags:
             - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }


