---

- name: Staging AWS Configuration for EAU
  hosts: home
  remote_user: ubuntu
  roles:
    - servergrove.symfony2

  vars:
    symfony2_project_root: /srv/eau
    symfony2_project_name: eau
    symfony2_project_composer_path: /srv/eau/shared
    symfony2_project_repo: git@github.com:orloc/evetool.git
    symfony2_project_branch: "staging"
    symfony2_project_php_path: php
    symfony2_project_env: prod
    symfony2_project_console_opts: '--no-debug'
    symfony2_project_composer_opts: '--no-dev --optimize-autoloader --no-interaction'
    symfony2_project_keep_releases: 3
    symfony2_project_clean_versioning: true