---

  - name: Fixing Permissions
    file: dest={{symfony2_project_root}}/releases/{{symfony2_project_release}}/app/cache mode=0777 recurse=true owner={{ server_user }}
    sudo: yes

  - name: Restarting php-fpm
    sudo: yes
    service: name=php5-fpm state=restarted

  - name: Check if nginx exists
    stat: path=/usr/sbin/nginx
    register: nginx_file

  - name: Restarting nginx
    sudo: yes
    service: name=nginx state=restarted
    when: nginx_file.stat.exists == true
