---

  - name: Fixing Permissions
    file: dest={{symfony2_project_root}}/releases/{{symfony2_project_release}}/app/cache mode=0777 recurse=true owner={{ server_user }}
    sudo: yes

  - name: Restarting php-fpm
    sudo: yes
    service: name=php5-fpm state=restarted

  - name: Restarting nginx
    sudo: yes
    service: name=nginx state=restarted
    when: sys.stat nginx is defined
